In [ ]:
import pandas as pd
from sqlalchemy import text

from literature_ai.db import ENGINE
from literature_ai.search_service.search.vector_search import vector_search_async
from literature_ai.search_service.search.keyword_search import keyword_search
from literature_ai.search_service.search.chunk_search import rag_paper_chunks, CHUNKS_TABLE
from literature_ai.search_service.data_collect.collect_full_papers import process_papers_by_id, FULLTEXT_TABLE

QUERY = "ML for optical coherence tomography diagnosis"

In [5]:
vector_results = await vector_search_async(QUERY, run_id=1, n_results=20)
display(pd.DataFrame(vector_results))

/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/filelock/_soft_rw/_async.py:10: RuntimeWarning: coroutine 'vector_search_async' was never awaited
  from ._sync import SoftReadWriteLock
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Fetching 4 files: 100%|██████████| 4/4 [00:00<00:00, 60787.01it/s]
Fetching 4 files: 100%|██████████| 4/4 [00:00<00:00, 92691.80it/s]
There are adapters available but none are activated for the forward pass.

,paperId,title,abstract,year,venue,citationCount,url,DOI,distance
0,b954efe5e46b8952f5a8daf42e7e535119b5408b,Development and Validation of a Deep Learning ...,None,2017,Journal of the American Medical Association (J...,2063,https://jamanetwork.com/journals/jama/articlep...,10.1001/jama.2017.18152,0.217084
1,5c45a5d05ac564adb67811eeb9d41d6460c70135,Development and Validation of a Deep Learning ...,None,2016,Journal of the American Medical Association (J...,6883,https://jamanetwork.com/journals/jama/articlep...,10.1001/jama.2016.17216,0.223362
2,ba913e2c03ece1c75f0af4d16dd11c7ffbc6e3ba,Diagnostic Assessment of Deep Learning Algorit...,None,2017,Journal of the American Medical Association (J...,3158,https://jamanetwork.com/journals/jama/articlep...,10.1001/jama.2017.14585,0.225067
3,dc0c84b7c5e6521216da789f8171544709120cf0,Opportunities and obstacles for deep learning ...,"Deep learning, which describes a class of mach...",2017,bioRxiv,2020,https://www.biorxiv.org/content/biorxiv/early/...,10.1098/rsif.2017.0387,0.227537
4,9406246f6972c03e5bfaac4df4676648dc4ac935,Deep Learning Techniques for Automatic MRI Car...,"Delineation of the left ventricular cavity, my...",2018,IEEE Transactions on Medical Imaging,2276,https://qmro.qmul.ac.uk/xmlui/bitstream/123456...,10.1109/TMI.2018.2837502,0.229409
5,89a816719613e220a64ab2590c938c23bbfe187e,CheXpert: A Large Chest Radiograph Dataset wit...,"Large, labeled datasets have driven deep learn...",2019,AAAI Conference on Artificial Intelligence,3583,https://aaai.org/ojs/index.php/AAAI/article/do...,10.1609/aaai.v33i01.3301590,0.234148
6,7ae2783a9196fb4bc2a610ae812d19722daddce5,Applications of machine learning to machine fa...,Abstract Intelligent fault diagnosis (IFD) ref...,2020,,2561,http://bura.brunel.ac.uk/bitstream/2438/20040/...,10.1016/j.ymssp.2019.106587,0.234960
7,6ff909c6fe089fc8ebfc64eca0f0c3cc34ba277f,A survey on deep learning in medical image ana...,"Deep learning algorithms, in particular convol...",2017,Medical Image Anal.,13760,https://ars.els-cdn.com/content/image/1-s2.0-S...,10.1016/j.media.2017.07.005,0.237867
8,8df72c48a7ce4418c683c4dd9bb300558ac71d47,"Deep learning for healthcare: review, opportun...",None,2018,Briefings Bioinform.,2627,https://europepmc.org/articles/pmc6455466?pdf=...,10.1093/bib/bbx044,0.240149
9,7ab0f0da686cd4094fd96f5a30e0b6072525fd09,Deep Learning in Medical Image Analysis,The computer-assisted analysis for better inte...,2017,Annual Review of Biomedical Engineering,2924,https://www.annualreviews.org/doi/pdf/10.1146/...,10.1146/annurev-bioeng-071516-044442,0.242201
10,58b6bd06ea58c367c64286126ba14128b45041b8,ChestX-Ray8: Hospital-Scale Chest X-Ray Databa...,The chest X-ray is one of the most commonly ac...,2017,Computer Vision and Pattern Recognition,3510,https://arxiv.org/pdf/1705.02315,10.1109/CVPR.2017.369,0.243409
11,3e358c3033908a9506e7f1e3cf29283e359f43d6,Data-efficient and weakly supervised computati...,Deep-learning methods for computational pathol...,2020,Nature Biomedical Engineering,2164,https://arxiv.org/pdf/2004.09666,10.1038/s41551-020-00682-w,0.243784
12,c53fa445bee435f567828db3a0ede0f08abdd0d5,Computational Radiomics System to Decode the R...,Radiomics aims to quantify phenotypic characte...,2017,Cancer Research,5390,https://cancerres.aacrjournals.org/content/can...,10.1158/0008-5472.CAN-17-0339,0.243918
13,5c7e5248d9eb7f373f10277410bf8506160907ea,All-optical machine learning using diffractive...,All-optical deep learning Deep learning uses m...,2018,Science,2263,https://arxiv.org/pdf/1804.08711,10.1126/science.aat8084,0.248091
14,d21703674ae562bae4a849a75847cdd9ead417df,Optimization Methods for Large-Scale Machine L...,This paper provides a review and commentary on...,2016,SIAM Review,3915,https://arxiv.org/pdf/1606.04838,10.1137/16M1080173,0.249116
15,7580c72df96488927c59a5f31a4b10784adfc749,Convolutional neural networks: an overview and...,"Convolutional neural network (CNN), a class of...",2018,Insights into Imaging,4036,https://insightsimaging.springeropen.com/track...,10.1007/s13244-018-0639-9,0.249648
16,e30d9b8ce108d982169621b88a5e3fb69fec70e1,Using Deep Learning for Image-Based Plant Dise...,Crop diseases are a major threat to food secur...,2016,Frontiers in Plant Science,4312,https://www.frontiersin.org/articles/10.3389/f...,10.3389/fpls.2016.01419,0.250870
17,5603fcb32aaae2f8d1597ccfe6009c14f54a7548,COVID-Net: a tailored deep convolutional neura...,The Coronavirus Disease 2019 (COVID-19) pandem...,2020,Scientific Reports,2740,https://www.nature.com/articles/s41598-020-765...,10.1038/s41598-020-76550-z,0.250938
18,0084f3cb0a1754272151c5268a783f24bf5676a0,"Review of deep learning: concepts, CNN archite...","In the last few years, the deep learning (DL) ...",2021,Journal of Big Data,6675,https://journalofbigdata.springeropen.com/coun...,10.1186/s40537-021-00444-8,0.251182
19,790a5020f730491f6a2f35ef7a2bb8c18d42d963,Covid-19: automatic detection from X-ray image...,"In this study, a dataset of X-ray images from ...",2020,Physical and Engineering Sciences in Medicine,2005,https://link.springer.com/content/pdf/10.1007/...,10.1007/s13246-020-00865-4,0.251907

In [6]:
keyword_results = keyword_search(QUERY, n_results=20)
display(pd.DataFrame(keyword_results))

Empty DataFrame
Columns: []
Index: []

In [7]:
paper_ids = [r["paperId"] for r in vector_results]
metrics = process_papers_by_id(paper_ids)

2026-09-04 17:39:57.441 | WARNING  | literature_ai.search_service.data_collect.collect_full_papers:download_pdf:73 - Failed to download https://jamanetwork.com/journals/jama/articlepdf/2665775/jama_ting_2017_oi_170140.pdf: 403 Client Error: Forbidden for url: https://jamanetwork.com/journals/jama/articlepdf/2665775/jama_ting_2017_oi_170140.pdf
2026-09-04 17:39:57.489 | WARNING  | literature_ai.search_service.data_collect.collect_full_papers:download_pdf:73 - Failed to download https://jamanetwork.com/journals/jama/articlepdf/2588763/joi160132.pdf: 403 Client Error: Forbidden for url: https://jamanetwork.com/journals/jama/articlepdf/2588763/joi160132.pdf
2026-09-04 17:39:57.532 | WARNING  | literature_ai.search_service.data_collect.collect_full_papers:download_pdf:73 - Failed to download https://jamanetwork.com/journals/jama/articlepdf/2665774/jama_ehteshami_bejnordi_2017_oi_170113.pdf: 403 Client Error: Forbidden for url: https://jamanetwork.com/journals/jama/articlepdf/2665774/jama_ehteshami_bejnordi_2017_oi_170113.pdf
2026-09-04 17:40:36.469 | ERROR    | literature_ai.search_service.data_collect.collect_full_papers:process_papers_by_id:205 - Unexpected error processing paperId='dc0c84b7c5e6521216da789f8171544709120cf0': asyncio.run() cannot be called from a running event loop
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ip...
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x109b41e40>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x109b302f0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel/kernelapp.py", line 807, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x109b78b80>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10a136900>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x109b302f0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x107dc6ac0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10a136900>
  File "/Users/adam/.pyenv/versions/3.13.11/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x107dc8900>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/adam/.pyenv/versions/3.13.11/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x107d56520>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x10a160ca0>()>
  File "/Users/adam/.pyenv/versions/3.13.11/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x10a160ca0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x10a160ca0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x10a160ca0>()>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'990ed833-faf'...36B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'57a5f824b403'...64B)>, <zmq.Frame(b'{"date":"202...
          │    └ <function Kernel.dispatch_shell at 0x109ad4b80>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x109b32e40>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x1274ea110>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'date': datetime.datetime(2026, 9, 4, 16, 39, 57, 315000, tzinfo=tzutc()), 'msg_id': '4b8a9e11-9b06-47a7-a598-cd0...
                                  │       └ [b'990ed833-faf6-4f38-84c5-59858b1e3de9']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10a145be0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x109e60ba0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 460, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x109b03380>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x109e95be0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel/zmqshell.py", line 665, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': 'vscode-notebook-cell:/Users/adam/Documents/Projects/Literature-Review-AI...
                             └ ('paper_ids = [r["paperId"] for r in vector_results]\nmetrics = process_papers_by_id(paper_ids)',)
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x108f1f600>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x109e95be0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x11a7d5a40>
             └ <function _pseudo_sync_runner at 0x108f05e40>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x11a7d5a40>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/9x/wcvflgqn6ps01qhjpcb4z2_h0000gn/T/ipykernel_83953/1644034000.py'
                       │    │             │        └ [<ast.Assign object at 0x1274c6d50>, <ast.Assign object at 0x1274c4ad0>]
                       │    │             └ <ast.Module object at 0x1274c41d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x108f1f9c0>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x109e95be0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 1273c6d50, execution_count=7 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x119d6a410, file "/var/folders/9x/wcvflgqn6ps01qhjpcb4z2_h0000gn/T/ipykernel_83953/1644034000.py", ...
             │    └ <function InteractiveShell.run_code at 0x108f1fa60>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x109e95be0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ <property object at 0x108efd4e0>
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x109e95be0>
         │         │    └ <property object at 0x108efd530>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x109e95be0>
         └ <code object <module> at 0x119d6a410, file "/var/folders/9x/wcvflgqn6ps01qhjpcb4z2_h0000gn/T/ipykernel_83953/1644034000.py", ...

  File "/var/folders/9x/wcvflgqn6ps01qhjpcb4z2_h0000gn/T/ipykernel_83953/1644034000.py", line 2, in <module>
    metrics = process_papers_by_id(paper_ids)
              │                    └ ['b954efe5e46b8952f5a8daf42e7e535119b5408b', '5c45a5d05ac564adb67811eeb9d41d6460c70135', 'ba913e2c03ece1c75f0af4d16dd11c7ffbc...
              └ <function process_papers_by_id at 0x119c9a480>

> File "/Users/adam/Documents/Projects/Literature-Review-AI/literature_ai/search_service/data_collect/collect_full_papers.py", line 178, in process_papers_by_id
    embeddings = asyncio.run(embed_chunk_texts(model, chunk_texts)) if chunk_texts else []
                 │       │   │                 │      │                └ ['Biology and medicine are rapidly becoming data-intensive. A recent comparison of genomics with social media, online videos,...
                 │       │   │                 │      └ ['Biology and medicine are rapidly becoming data-intensive. A recent comparison of genomics with social media, online videos,...
                 │       │   │                 └ <literature_ai.search_service.embeddings.core.OpenAiEmbedding object at 0x1274a3230>
                 │       │   └ <function embed_chunk_texts at 0x119c9a3e0>
                 │       └ <function run at 0x107958f40>
                 └ <module 'asyncio' from '/Users/adam/.pyenv/versions/3.13.11/lib/python3.13/asyncio/__init__.py'>

  File "/Users/adam/.pyenv/versions/3.13.11/lib/python3.13/asyncio/runners.py", line 191, in run
    raise RuntimeError(

RuntimeError: asyncio.run() cannot be called from a running event loop
2026-09-04 17:40:36.758 | WARNING  | literature_ai.search_service.data_collect.collect_full_papers:download_pdf:73 - Failed to download https://qmro.qmul.ac.uk/xmlui/bitstream/123456789/42264/1/Bernard%20et%20al_Deep%20learning%20techniques%20automatic%20MRI_2018_Accepted.pdf: 404 Client Error: Not found for url: https://qmro.qmul.ac.uk/xmlui/bitstream/123456789/42264/1/Bernard%20et%20al_Deep%20learning%20techniques%20automatic%20MRI_2018_Accepted.pdf
2026-09-04 17:40:37.272 | WARNING  | literature_ai.search_service.data_collect.collect_full_papers:download_pdf:73 - Failed to download https://aaai.org/ojs/index.php/AAAI/article/download/3834/3712: 403 Client Error: Forbidden for url: https://aaai.org/ojs/index.php/AAAI/article/download/3834/3712
2026-09-04 17:41:03.105 | ERROR    | literature_ai.search_service.data_collect.collect_full_papers:process_papers_by_id:205 - Unexpected error processing paperId='7ae2783a9196fb4bc2a610ae812d19722daddce5': asyncio.run() cannot be called from a running event loop
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ip...
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x109b41e40>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x109b302f0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel/kernelapp.py", line 807, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x109b78b80>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10a136900>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x109b302f0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x107dc6ac0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10a136900>
  File "/Users/adam/.pyenv/versions/3.13.11/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x107dc8900>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/adam/.pyenv/versions/3.13.11/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x107d56520>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x10a160ca0>()>
  File "/Users/adam/.pyenv/versions/3.13.11/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x10a160ca0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x10a160ca0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x10a160ca0>()>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
          │    │              │                └ None
          │    │              └ [<zmq.Frame(b'990ed833-faf'...36B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'57a5f824b403'...64B)>, <zmq.Frame(b'{"date":"202...
          │    └ <function Kernel.dispatch_shell at 0x109ad4b80>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x109b32e40>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x1274ea110>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'date': datetime.datetime(2026, 9, 4, 16, 39, 57, 315000, tzinfo=tzutc()), 'msg_id': '4b8a9e11-9b06-47a7-a598-cd0...
                                  │       └ [b'990ed833-faf6-4f38-84c5-59858b1e3de9']
                                  └ <zmq.Socket(zmq.PAIR) at 0x10a145be0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x109e60ba0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 460, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x109b03380>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x109e95be0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/ipykernel/zmqshell.py", line 665, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': 'vscode-notebook-cell:/Users/adam/Documents/Projects/Literature-Review-AI...
                             └ ('paper_ids = [r["paperId"] for r in vector_results]\nmetrics = process_papers_by_id(paper_ids)',)
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3170, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x108f1f600>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x109e95be0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3225, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x11a7d5a40>
             └ <function _pseudo_sync_runner at 0x108f05e40>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x11a7d5a40>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3447, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/9x/wcvflgqn6ps01qhjpcb4z2_h0000gn/T/ipykernel_83953/1644034000.py'
                       │    │             │        └ [<ast.Assign object at 0x1274c6d50>, <ast.Assign object at 0x1274c4ad0>]
                       │    │             └ <ast.Module object at 0x1274c41d0>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x108f1f9c0>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x109e95be0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3688, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 1273c6d50, execution_count=7 error_before_exec=None error_in_exec=None info=<ExecutionInfo object ...
             │    │        └ <code object <module> at 0x119d6a410, file "/var/folders/9x/wcvflgqn6ps01qhjpcb4z2_h0000gn/T/ipykernel_83953/1644034000.py", ...
             │    └ <function InteractiveShell.run_code at 0x108f1fa60>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x109e95be0>
  File "/Users/adam/Documents/Projects/Literature-Review-AI/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

KeyboardInterrupt:

In [ ]:
print(metrics.inserted)

In [ ]:
with ENGINE.connect() as conn:
    rows = conn.execute(
        text('SELECT "paperId" FROM {} WHERE "paperId" = ANY(:ids) AND "status" = \'success\''.format(FULLTEXT_TABLE)),
        {"ids": paper_ids},
    ).fetchall()
successful_ids = [r[0] for r in rows]

for paper_id in successful_ids:
    with ENGINE.connect() as conn:
        rows = conn.execute(
            text('SELECT section_header FROM {} WHERE "paperId" = :id ORDER BY section_index'.format(CHUNKS_TABLE)),
            {"id": paper_id},
        ).fetchall()
    headers = list(dict.fromkeys(r[0] for r in rows))
    print(paper_id, headers)

In [ ]:
rag_results = rag_paper_chunks(successful_ids, QUERY, n_results=10)
display(pd.DataFrame(rag_results["results"]))