In [21]:
from papery.core.api.core import api_call

data = await api_call(
    params={"query": "machine learning medical diagnosis", "fields": "title,abstract"},
    api_id="semantic_scholar_api",
    endpoint="graph/v1/paper/search/bulk/",
)

import pandas as pd

results = pd.DataFrame(data.get("data", None))
display(results)

2026-02-10 23:04:56.033 | INFO     | papery.core.api.core:api_call:30 - Adding item {'query': 'machine learning medical diagnosis', 'fields': 'title,abstract'} to queue...
2026-02-10 23:04:56.034 | INFO     | papery.core.api.dispatcher:add_to_queue:81 - Adding to queue: {'query': 'machine learning medical diagnosis', 'fields': 'title,abstract'}
2026-02-10 23:04:56.034 | INFO     | papery.core.api.dispatcher:add_to_queue:83 - Queue size is now 1

,paperId,title,openAccessPdf,authors,abstract
0,0002147f6944bce6f6199476a5e2bd6ed3ac0e9c,MACHINE LEARNING APPROACH FOR LUNG CANCER DETE...,"{'url': '', 'status': None, 'license': None}","[{'authorId': '2153292749', 'name': 'Swati Muk...",None
1,0002ff9cac5accdefb66a0124a14ee15a7519542,Uma solução de aprendizagem de máquina para de...,{'url': 'https://doi.org/10.5753/sbsi.2020.131...,"[{'authorId': '2067893998', 'name': 'Francis S...",Keratoconus is a problem that causes changes i...
2,000b7b5ffe89da08f5b1ae5c11fed3f7e2e83fc4,A PERCEPTIVE SURVEY ON THE PREDICTION OF DISEA...,"{'url': '', 'status': None, 'license': None, '...","[{'authorId': '2369443376', 'name': 'Femila K....",Massive volumes of data are routinely handled ...
3,000be47a3dd48228bed143861ee0e0711d09db16,An algorithm for characterizing skin moles usi...,{'url': 'https://doi.org/10.11591/ijece.v11i4....,"[{'authorId': '2075837719', 'name': 'Zaid Sanc...","Melanoma, the most serious type of skin cancer..."
4,00129c0f142ae6a14e510a5b7a9ead97417f40bc,Bridging Healthcare Gaps: Sustainable Liver Di...,"{'url': '', 'status': 'CLOSED', 'license': Non...","[{'authorId': '2352103469', 'name': 'Kunal Jha...","Liver disease is a major global health issue, ..."
...,...,...,...,...,...
995,107163668e16fd83743ef7857c92c022f0d1c86a,Independent Weighted Feature Set with Linked F...,{'url': 'https://ijritcc.org/index.php/ijritcc...,"[{'authorId': '2156272979', 'name': 'M. Kumar'...",Lung cancer is a potentially fatal disease tha...
996,10788ca624edbfd06526f48ad48f1369c3f19ee0,Contrast-enhanced computed tomography-based in...,"{'url': '', 'status': None, 'license': 'CCBYNC...","[{'authorId': None, 'name': 'Zhiqiang Peng'}, ...",Background Lung cancer remains the leading cau...
997,107ade6be083625b818eb4d0a58b34a6c3e07dfb,Deep Learning for Analysis of Electronic Healt...,"{'url': '', 'status': None, 'license': None, '...","[{'authorId': '1453623768', 'name': 'Pawan Sin...",None
998,107f5cdd459040d1069e747a2caade2882496fa6,Tiny Machine Learning (TinyML) Based Self Diag...,"{'url': '', 'status': 'CLOSED', 'license': Non...","[{'authorId': '2135573288', 'name': 'Samson Ot...",The World Health Organization (WHO) 2022 stati...
999,1088660145e06aee4dd99f9886802f17362d586e,DeepATsers: a deep learning framework for one-...,"{'url': '', 'status': None, 'license': 'CCBY',...","[{'authorId': '2352122025', 'name': 'Ankhbayar...",The integration of Artificial Intelligence (AI...

,paperId,isOpenAccess,fieldsOfStudy,publicationTypes
0,0002147f6944bce6f6199476a5e2bd6ed3ac0e9c,False,[Computer Science],None
1,0002ff9cac5accdefb66a0124a14ee15a7519542,True,None,None
2,000b7b5ffe89da08f5b1ae5c11fed3f7e2e83fc4,False,None,"[JournalArticle, Review]"
3,000be47a3dd48228bed143861ee0e0711d09db16,True,[Computer Science],None
4,00129c0f142ae6a14e510a5b7a9ead97417f40bc,False,None,[Conference]
...,...,...,...,...
995,107163668e16fd83743ef7857c92c022f0d1c86a,True,None,[JournalArticle]
996,10788ca624edbfd06526f48ad48f1369c3f19ee0,False,[Medicine],[JournalArticle]
997,107ade6be083625b818eb4d0a58b34a6c3e07dfb,False,[Computer Science],None
998,107f5cdd459040d1069e747a2caade2882496fa6,False,[Computer Science],"[JournalArticle, Conference]"
999,1088660145e06aee4dd99f9886802f17362d586e,False,[Medicine],[JournalArticle]

In [7]:
from papery.core.db import save_table_async, load_table

await save_table_async(
    results, table_path="public.test_papers_basic", if_exists="append"
)

In [8]:
load_table("public.test_papers_basic")

,paperId,title
0,0002147f6944bce6f6199476a5e2bd6ed3ac0e9c,MACHINE LEARNING APPROACH FOR LUNG CANCER DETE...
1,0002ff9cac5accdefb66a0124a14ee15a7519542,Uma solução de aprendizagem de máquina para de...
2,000b7b5ffe89da08f5b1ae5c11fed3f7e2e83fc4,A PERCEPTIVE SURVEY ON THE PREDICTION OF DISEA...
3,000be47a3dd48228bed143861ee0e0711d09db16,An algorithm for characterizing skin moles usi...
4,00129c0f142ae6a14e510a5b7a9ead97417f40bc,Bridging Healthcare Gaps: Sustainable Liver Di...
...,...,...
2995,107163668e16fd83743ef7857c92c022f0d1c86a,Independent Weighted Feature Set with Linked F...
2996,10788ca624edbfd06526f48ad48f1369c3f19ee0,Contrast-enhanced computed tomography-based in...
2997,107ade6be083625b818eb4d0a58b34a6c3e07dfb,Deep Learning for Analysis of Electronic Healt...
2998,107f5cdd459040d1069e747a2caade2882496fa6,Tiny Machine Learning (TinyML) Based Self Diag...
2999,1088660145e06aee4dd99f9886802f17362d586e,DeepATsers: a deep learning framework for one-...